// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYZx10GEnDRb9rUncJ_ilE1tAt7uepDIE',
    appId: '1:491579379138:web:06330d7c320da722845a5b',
    messagingSenderId: '491579379138',
    projectId: 'asroo-store-31843',
    authDomain: 'asroo-store-31843.firebaseapp.com',
    storageBucket: 'asroo-store-31843.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOvnjA3bQMshhVHBDtpuE0BG_JBHQiTaI',
    appId: '1:491579379138:android:07aaeb54548c8a55845a5b',
    messagingSenderId: '491579379138',
    projectId: 'asroo-store-31843',
    storageBucket: 'asroo-store-31843.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi4NkNmq99aLRcwq91AttsMYZDH2huQYA',
    appId: '1:491579379138:ios:ea540c250a052b75845a5b',
    messagingSenderId: '491579379138',
    projectId: 'asroo-store-31843',
    storageBucket: 'asroo-store-31843.appspot.com',
    iosBundleId: 'com.example.completeStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAi4NkNmq99aLRcwq91AttsMYZDH2huQYA',
    appId: '1:491579379138:ios:ea540c250a052b75845a5b',
    messagingSenderId: '491579379138',
    projectId: 'asroo-store-31843',
    storageBucket: 'asroo-store-31843.appspot.com',
    iosBundleId: 'com.example.completeStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYZx10GEnDRb9rUncJ_ilE1tAt7uepDIE',
    appId: '1:491579379138:web:abed8442107abe7d845a5b',
    messagingSenderId: '491579379138',
    projectId: 'asroo-store-31843',
    authDomain: 'asroo-store-31843.firebaseapp.com',
    storageBucket: 'asroo-store-31843.appspot.com',
  );
}
